{% set version = "0.9.3" %}

package:
  name: transitions
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/transitions/transitions-{{ version }}.tar.gz
  sha256: 881fb75bb1654ed55d86060bb067f2c716f8e155f57bb73fd444e53713aafec8

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - six
    - setuptools
  run:
    - python >={{ python_min }}
    - six

test:
  source_files:
    - examples
    - tests
  requires:
    - dill
    - mock
    - pytest
    - pytest-cov
    - pycodestyle
    - pygraphviz  # [not win]
    - python-graphviz
    - pip
    - python {{ python_min }}
  imports:
    - transitions
  commands:
    - pip check
    - pytest -vv --pyargs -k "not conformance" --cov=transitions --cov-report=term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/pytransitions/transitions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight, object-oriented finite state machine implementation in Python

extra:
  recipe-maintainers:
    - bollwyvl
