{% set version = "0.9.2" %}

package:
  name: transitions
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/transitions/transitions-{{ version }}.tar.gz
  sha256: 2f8490dbdbd419366cef1516032ab06d07ccb5839ef54905e842a472692d4204

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - six
  run:
    - python >=2.7
    - six

test:
  source_files:
    - examples
    - tests
  requires:
    - dill
    - mock
    - pytest
    - pytest-cov
    - pycodestyle
    - pygraphviz  # [not win]
    - python-graphviz
    - pip
  imports:
    - transitions
  commands:
    - python -m pip check
    - pytest -vv --pyargs -k "not conformance" --cov=transitions --cov-report=term-missing:skip-covered --no-cov-on-fail

about:
  home: https://github.com/pytransitions/transitions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A lightweight, object-oriented finite state machine implementation in Python

extra:
  recipe-maintainers:
    - bollwyvl
